//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idealde.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idealde.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idealde.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} before exit?.
        /// </summary>
        internal static string AskForSaveFileBeforeExit {
            get {
                return ResourceManager.GetString("AskForSaveFileBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile And Run.
        /// </summary>
        internal static string CompileAndRunSingleFileCommandText {
            get {
                return ResourceManager.GetString("CompileAndRunSingleFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-compile selected file, run it right after compilation complete.
        /// </summary>
        internal static string CompileAndRunSingleFileCommandTooltip {
            get {
                return ResourceManager.GetString("CompileAndRunSingleFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Single Selected Item.
        /// </summary>
        internal static string CompileSingleFileCommandText {
            get {
                return ResourceManager.GetString("CompileSingleFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile only selected file, not work if it depends on other file(s).
        /// </summary>
        internal static string CompileSingleFileCommandTooltip {
            get {
                return ResourceManager.GetString("CompileSingleFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        internal static string CreateNewFileText {
            get {
                return ResourceManager.GetString("CreateNewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string EditCopyCommandText {
            get {
                return ResourceManager.GetString("EditCopyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditCopyCommandTooltip {
            get {
                return ResourceManager.GetString("EditCopyCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string EditCutCommandText {
            get {
                return ResourceManager.GetString("EditCutCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditCutCommandTooltip {
            get {
                return ResourceManager.GetString("EditCutCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find And Replace.
        /// </summary>
        internal static string EditFindAndReplaceCommandText {
            get {
                return ResourceManager.GetString("EditFindAndReplaceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditFindAndReplaceCommandTooltip {
            get {
                return ResourceManager.GetString("EditFindAndReplaceCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        internal static string EditGotoCommadText {
            get {
                return ResourceManager.GetString("EditGotoCommadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditGotoCommandTooltip {
            get {
                return ResourceManager.GetString("EditGotoCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string EditPasteCommandText {
            get {
                return ResourceManager.GetString("EditPasteCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditPasteCommandTooltip {
            get {
                return ResourceManager.GetString("EditPasteCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string EditRedoCommandText {
            get {
                return ResourceManager.GetString("EditRedoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditRedoCommandTooltip {
            get {
                return ResourceManager.GetString("EditRedoCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectAll.
        /// </summary>
        internal static string EditSelectAllCommandText {
            get {
                return ResourceManager.GetString("EditSelectAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditSelectAllCommandTooltip {
            get {
                return ResourceManager.GetString("EditSelectAllCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string EditUndoCommandText {
            get {
                return ResourceManager.GetString("EditUndoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EditUndoCommandTooltip {
            get {
                return ResourceManager.GetString("EditUndoCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string FileCloseCommandText {
            get {
                return ResourceManager.GetString("FileCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0}.
        /// </summary>
        internal static string FileCloseCommandTooltip {
            get {
                return ResourceManager.GetString("FileCloseCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Header (.h).
        /// </summary>
        internal static string FileNewCppHeaderCommandText {
            get {
                return ResourceManager.GetString("FileNewCppHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New C++ .h Header File.
        /// </summary>
        internal static string FileNewCppHeaderCommandTooltip {
            get {
                return ResourceManager.GetString("FileNewCppHeaderCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Source (.cpp).
        /// </summary>
        internal static string FileNewCppSourceCommandText {
            get {
                return ResourceManager.GetString("FileNewCppSourceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New C++ .cpp Source File.
        /// </summary>
        internal static string FileNewCppSourceCommandTooltip {
            get {
                return ResourceManager.GetString("FileNewCppSourceCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Source (.cpp).
        /// </summary>
        internal static string FileNewCppSourceMenuText {
            get {
                return ResourceManager.GetString("FileNewCppSourceMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string FileNewMenuText {
            get {
                return ResourceManager.GetString("FileNewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileOpenCommandText {
            get {
                return ResourceManager.GetString("FileOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open An Existing File.
        /// </summary>
        internal static string FileOpenCommandTooltip {
            get {
                return ResourceManager.GetString("FileOpenCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Item As.
        /// </summary>
        internal static string FileSaveAsCommandText {
            get {
                return ResourceManager.GetString("FileSaveAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} As New File.
        /// </summary>
        internal static string FileSaveAsCommandTooltip {
            get {
                return ResourceManager.GetString("FileSaveAsCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Item.
        /// </summary>
        internal static string FileSaveCommandText {
            get {
                return ResourceManager.GetString("FileSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        internal static string FileSaveCommandTooltip {
            get {
                return ResourceManager.GetString("FileSaveCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder {
            get {
                object obj = ResourceManager.GetObject("folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        internal static string RunBuildCommandText {
            get {
                return ResourceManager.GetString("RunBuildCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RunBuildCommandTooltip {
            get {
                return ResourceManager.GetString("RunBuildCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string RunCommandText {
            get {
                return ResourceManager.GetString("RunCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RunCommandTooltip {
            get {
                return ResourceManager.GetString("RunCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string RunMenuText {
            get {
                return ResourceManager.GetString("RunMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        internal static string RunRebuildCommandText {
            get {
                return ResourceManager.GetString("RunRebuildCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RunRebuildCommandTooltip {
            get {
                return ResourceManager.GetString("RunRebuildCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Single Selected Item.
        /// </summary>
        internal static string RunSingleFileCommandText {
            get {
                return ResourceManager.GetString("RunSingleFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run built output file of current selected item, auto compile if it wasn&apos;t built yet.
        /// </summary>
        internal static string RunSingleFileCommandTooltip {
            get {
                return ResourceManager.GetString("RunSingleFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string UntitledFileName {
            get {
                return ResourceManager.GetString("UntitledFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        internal static string ViewErrorListCommandText {
            get {
                return ResourceManager.GetString("ViewErrorListCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error List Tool Window.
        /// </summary>
        internal static string ViewErrorListCommandTooltip {
            get {
                return ResourceManager.GetString("ViewErrorListCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        internal static string ViewOutputCommandText {
            get {
                return ResourceManager.GetString("ViewOutputCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Output Tool Window.
        /// </summary>
        internal static string ViewOutputCommandTooltip {
            get {
                return ResourceManager.GetString("ViewOutputCommandTooltip", resourceCulture);
            }
        }
    }
}
