//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Idealde.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Idealde.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New C++ Header (.h).
        /// </summary>
        public static string AddNewCppHeaderToProjectCommandText {
            get {
                return ResourceManager.GetString("AddNewCppHeaderToProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddNewCppHeaderToProjectCommandTooltip {
            get {
                return ResourceManager.GetString("AddNewCppHeaderToProjectCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New C++ Source (.cpp).
        /// </summary>
        public static string AddNewCppSourceToProjectCommandText {
            get {
                return ResourceManager.GetString("AddNewCppSourceToProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AddNewCppSourceToProjectCommandTooltip {
            get {
                return ResourceManager.GetString("AddNewCppSourceToProjectCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idealde.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you want to close project {0}?.
        /// </summary>
        public static string AreYouWantToCloseProjectText {
            get {
                return ResourceManager.GetString("AreYouWantToCloseProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} before exit?.
        /// </summary>
        public static string AskForSaveFileBeforeExit {
            get {
                return ResourceManager.GetString("AskForSaveFileBeforeExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Project Root Path.
        /// </summary>
        public static string BrowseProjectRootPathDisplayText {
            get {
                return ResourceManager.GetString("BrowseProjectRootPathDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile And Run.
        /// </summary>
        public static string CompileAndRunSingleFileCommandText {
            get {
                return ResourceManager.GetString("CompileAndRunSingleFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-compile selected file, run it right after compilation complete.
        /// </summary>
        public static string CompileAndRunSingleFileCommandTooltip {
            get {
                return ResourceManager.GetString("CompileAndRunSingleFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compiler.
        /// </summary>
        public static string CompilerSettingsName {
            get {
                return ResourceManager.GetString("CompilerSettingsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CompilerSettingsPath {
            get {
                return ResourceManager.GetString("CompilerSettingsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile Single Selected Item.
        /// </summary>
        public static string CompileSingleFileCommandText {
            get {
                return ResourceManager.GetString("CompileSingleFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile only selected file, not work if it depends on other file(s).
        /// </summary>
        public static string CompileSingleFileCommandTooltip {
            get {
                return ResourceManager.GetString("CompileSingleFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile failed.
        /// </summary>
        public static string CompileSingleFileFailedOutput {
            get {
                return ResourceManager.GetString("CompileSingleFileFailedOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile successfully.
        /// </summary>
        public static string CompileSingleFileFinishSuccessfullyOutput {
            get {
                return ResourceManager.GetString("CompileSingleFileFinishSuccessfullyOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile single file start.
        /// </summary>
        public static string CompileSingleFileStartOutput {
            get {
                return ResourceManager.GetString("CompileSingleFileStartOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New File.
        /// </summary>
        public static string CreateNewFileText {
            get {
                return ResourceManager.GetString("CreateNewFileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cann&apos;t create project.
        /// </summary>
        public static string CreateProjectFailedText {
            get {
                return ResourceManager.GetString("CreateProjectFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string EditCopyCommandText {
            get {
                return ResourceManager.GetString("EditCopyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditCopyCommandTooltip {
            get {
                return ResourceManager.GetString("EditCopyCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string EditCutCommandText {
            get {
                return ResourceManager.GetString("EditCutCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditCutCommandTooltip {
            get {
                return ResourceManager.GetString("EditCutCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find And Replace.
        /// </summary>
        public static string EditFindAndReplaceCommandText {
            get {
                return ResourceManager.GetString("EditFindAndReplaceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditFindAndReplaceCommandTooltip {
            get {
                return ResourceManager.GetString("EditFindAndReplaceCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to.
        /// </summary>
        public static string EditGotoCommadText {
            get {
                return ResourceManager.GetString("EditGotoCommadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditGotoCommandTooltip {
            get {
                return ResourceManager.GetString("EditGotoCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditMenuText {
            get {
                return ResourceManager.GetString("EditMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string EditPasteCommandText {
            get {
                return ResourceManager.GetString("EditPasteCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditPasteCommandTooltip {
            get {
                return ResourceManager.GetString("EditPasteCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string EditRedoCommandText {
            get {
                return ResourceManager.GetString("EditRedoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditRedoCommandTooltip {
            get {
                return ResourceManager.GetString("EditRedoCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string EditSelectAllCommandText {
            get {
                return ResourceManager.GetString("EditSelectAllCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditSelectAllCommandTooltip {
            get {
                return ResourceManager.GetString("EditSelectAllCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string EditUndoCommandText {
            get {
                return ResourceManager.GetString("EditUndoCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string EditUndoCommandTooltip {
            get {
                return ResourceManager.GetString("EditUndoCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string ErrorsDisplayText {
            get {
                return ResourceManager.GetString("ErrorsDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string FileCloseCommandText {
            get {
                return ResourceManager.GetString("FileCloseCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0}.
        /// </summary>
        public static string FileCloseCommandTooltip {
            get {
                return ResourceManager.GetString("FileCloseCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileMenuText {
            get {
                return ResourceManager.GetString("FileMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Header (.h).
        /// </summary>
        public static string FileNewCppHeaderCommandText {
            get {
                return ResourceManager.GetString("FileNewCppHeaderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New C++ .h Header File.
        /// </summary>
        public static string FileNewCppHeaderCommandTooltip {
            get {
                return ResourceManager.GetString("FileNewCppHeaderCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Project.
        /// </summary>
        public static string FileNewCppProjectCommandText {
            get {
                return ResourceManager.GetString("FileNewCppProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Empty C++Project.
        /// </summary>
        public static string FileNewCppProjectCommandTooltip {
            get {
                return ResourceManager.GetString("FileNewCppProjectCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Source (.cpp).
        /// </summary>
        public static string FileNewCppSourceCommandText {
            get {
                return ResourceManager.GetString("FileNewCppSourceCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New C++ .cpp Source File.
        /// </summary>
        public static string FileNewCppSourceCommandTooltip {
            get {
                return ResourceManager.GetString("FileNewCppSourceCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C++ Source (.cpp).
        /// </summary>
        public static string FileNewCppSourceMenuText {
            get {
                return ResourceManager.GetString("FileNewCppSourceMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FileNewFolderCommandText {
            get {
                return ResourceManager.GetString("FileNewFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new folder.
        /// </summary>
        public static string FileNewFolderCommandTooltip {
            get {
                return ResourceManager.GetString("FileNewFolderCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string FileNewMenuText {
            get {
                return ResourceManager.GetString("FileNewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File doesn&apos;t exist.
        /// </summary>
        public static string FileNotExistText {
            get {
                return ResourceManager.GetString("FileNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileOpenFileCommandText {
            get {
                return ResourceManager.GetString("FileOpenFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open An Existing File.
        /// </summary>
        public static string FileOpenFileCommandTooltip {
            get {
                return ResourceManager.GetString("FileOpenFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpenMenuText {
            get {
                return ResourceManager.GetString("FileOpenMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string FileOpenProjectCommandText {
            get {
                return ResourceManager.GetString("FileOpenProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open An Existing Project.
        /// </summary>
        public static string FileOpenProjectCommandTooltip {
            get {
                return ResourceManager.GetString("FileOpenProjectCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string FileRemoveCommandText {
            get {
                return ResourceManager.GetString("FileRemoveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove file from project.
        /// </summary>
        public static string FileRemoveCommandTooltip {
            get {
                return ResourceManager.GetString("FileRemoveCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Item As.
        /// </summary>
        public static string FileSaveAsCommandText {
            get {
                return ResourceManager.GetString("FileSaveAsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} As New File.
        /// </summary>
        public static string FileSaveAsCommandTooltip {
            get {
                return ResourceManager.GetString("FileSaveAsCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Selected Item.
        /// </summary>
        public static string FileSaveCommandText {
            get {
                return ResourceManager.GetString("FileSaveCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string FileSaveCommandTooltip {
            get {
                return ResourceManager.GetString("FileSaveCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string MessagesDisplayText {
            get {
                return ResourceManager.GetString("MessagesDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        public static string NewItemWindowTitle {
            get {
                return ResourceManager.GetString("NewItemWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProjectWindowTitle {
            get {
                return ResourceManager.GetString("NewProjectWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenFileDialogTitle {
            get {
                return ResourceManager.GetString("OpenFileDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter item name.
        /// </summary>
        public static string PleaseEnterItemNameText {
            get {
                return ResourceManager.GetString("PleaseEnterItemNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter project name.
        /// </summary>
        public static string PleaseEnterProjectNameText {
            get {
                return ResourceManager.GetString("PleaseEnterProjectNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project file doesn&apos;t exist..
        /// </summary>
        public static string ProjectFileNotExistText {
            get {
                return ResourceManager.GetString("ProjectFileNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project root directory not exist.
        /// </summary>
        public static string ProjectRootDirectoryNotExistText {
            get {
                return ResourceManager.GetString("ProjectRootDirectoryNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string RunBuildCommandText {
            get {
                return ResourceManager.GetString("RunBuildCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RunBuildCommandTooltip {
            get {
                return ResourceManager.GetString("RunBuildCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunCommandText {
            get {
                return ResourceManager.GetString("RunCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RunCommandTooltip {
            get {
                return ResourceManager.GetString("RunCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string RunMenuText {
            get {
                return ResourceManager.GetString("RunMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild.
        /// </summary>
        public static string RunRebuildCommandText {
            get {
                return ResourceManager.GetString("RunRebuildCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RunRebuildCommandTooltip {
            get {
                return ResourceManager.GetString("RunRebuildCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Single Selected Item.
        /// </summary>
        public static string RunSingleFileCommandText {
            get {
                return ResourceManager.GetString("RunSingleFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run built output file of current selected item, auto compile if it wasn&apos;t built yet.
        /// </summary>
        public static string RunSingleFileCommandTooltip {
            get {
                return ResourceManager.GetString("RunSingleFileCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same name item existed.
        /// </summary>
        public static string TheSameNameItemExistText {
            get {
                return ResourceManager.GetString("TheSameNameItemExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownDisplayText {
            get {
                return ResourceManager.GetString("UnknownDisplayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string UntitledFileName {
            get {
                return ResourceManager.GetString("UntitledFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error List.
        /// </summary>
        public static string ViewErrorListCommandText {
            get {
                return ResourceManager.GetString("ViewErrorListCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Error List Tool Window.
        /// </summary>
        public static string ViewErrorListCommandTooltip {
            get {
                return ResourceManager.GetString("ViewErrorListCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ViewMenuText {
            get {
                return ResourceManager.GetString("ViewMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output.
        /// </summary>
        public static string ViewOutputCommandText {
            get {
                return ResourceManager.GetString("ViewOutputCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Output Tool Window.
        /// </summary>
        public static string ViewOutputCommandTooltip {
            get {
                return ResourceManager.GetString("ViewOutputCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Explorer.
        /// </summary>
        public static string ViewProjectExplorerCommadText {
            get {
                return ResourceManager.GetString("ViewProjectExplorerCommadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project Explorer Tool Window.
        /// </summary>
        public static string ViewProjectExplorerCommandTooltip {
            get {
                return ResourceManager.GetString("ViewProjectExplorerCommandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings.
        /// </summary>
        public static string WarningsDisplayText {
            get {
                return ResourceManager.GetString("WarningsDisplayText", resourceCulture);
            }
        }
    }
}
